config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/how_the_other_half_lives', to: 'static_pages#how_the_other_half_lives' 
  get '/hopes_and_dreams', to: 'static_pages#hopes_and_dreams'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def hello
    # render html: "HOW THE OTHER HALF LIVE."
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def how_the_other_half_lives
  end

  def hopes_and_dreams
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Finchterest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/static_pages/home.html.erb
<!-- <html style="text-align: center; background-color: #e6dcd1">
	<div id="bg">
		<img src="cory_galifinakis.jpg" alt="Finchinakis" height="500" width="400">
	</div>
	<ul style="list-style-type: none">
		<li>
			<h1 style="font-family: Avantgarde, sans-serif">Can Someone let me borrow a can of scrubbing bubbles? I'm not wasted. This is a serious post.</h1>			
		</li>
	</ul>
	
</html>
 -->

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Finchterest</title>
</head>
<body class="home">
	<div class="container">
		<div class="header clearfix">
			<nav>
				<ul class="nav nav-pills pull-right">
					<li><%= link_to "Home", root_path, class: "active", role: "presentation" %></li>
					<li><%= link_to("Hopes & Dreams", hopes_and_dreams_path , class: "active", role: "presentation")%></li>
					<li><%= link_to("How The Other Half Lives", how_the_other_half_lives_path , class: "active", role: "presentation") %></li>
				</ul>
			</nav>
			<h3 class="text-muted">Finchterest</h3>
		</div>

		<div class="jumbotron">
			<img src="cory_galifinakis.jpg" alt="Finchinakis" height="400" width="300" class="img-circle">
			<p class="lead quote"><bold>Can someone let me borrow a can of scrubbing bubbles? I'm not wasted. This is a serious post.</bold></p>
			<p><a class="btn btn-primary" href="#">Sign up</a></p>		
		</div>
	</div>
</body>
</html>

app/views/static_pages/hopes_and_dreams.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Hopes & Dreams</title>
</head>
<body class="home">
	<h1 style="font-size: 60px; text-align: center; color: red">She had...</h1>
</body>
</html>

app/views/static_pages/how_the_other_half_lives.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>How The Other Half Lives</title>
</head>
<body id="htohl">
	
</body>
</html>